### ISSUE TITLE
qb-cityhall error

### ISSUE THREAD

**Issue by XXXTandem** [morais5/QBCore-Morais#12] opened 2021-03-27 02:27 UTC
Clicking on the qb-cityhall menu brings up this error[
![FiveM 2021-03-26 10_21_56 PM](https://user-images.githubusercontent.com/64930059/112707500-581b2a00-8e82-11eb-95af-72fc4f9ccca4.png)
](url)

**Comment by morais5** [comment] 2021-03-27 11:45
Duplicate of #13

**Closed by morais5** 2021-03-27 11:45 UTC
Labels: bug
